#!/usr/bin/env node
// Derived-file merge driver. A derived file (the documentation manifest, the host
// distributions, the vendored script copies) is regenerated from its sources and never
// hand-merged, so two branches that both regenerated it must not conflict on it.
//
//   node scripts/derived-merge.mjs install       register the driver and its attributes
//   node scripts/derived-merge.mjs check         exit 1 unless the driver is registered
//   node scripts/derived-merge.mjs regenerate    run from pre-commit and pre-merge-commit
//   node scripts/derived-merge.mjs amend         run from post-merge
//   node scripts/derived-merge.mjs reconcile     restamp the manifest of any merge, even with no conflict
//   node scripts/derived-merge.mjs rewrite       restamp the manifest after a rebase, from post-rewrite
//   node scripts/derived-merge.mjs driver %O %A %B %P    git calls this, never a person
//
// WHY two phases: git runs a merge driver once per file, before the merged tree exists on disk.
// A generator that ran inside the driver would read half-merged sources and write a wrong file.
// So the driver only records the path, and the merge result is regenerated by the commit hooks
// after every file, derived or not, has its merged content. A regeneration that fails restores the
// conflict in the index, so the merge cannot be committed with a stale file.
//
// A clean automatic merge needs one more step. Git writes that merge commit from the tree it
// merged before the pre-merge-commit hook ran, so the hook's regenerated files stay staged and miss
// the commit. The hook regenerates anyway, because a failure there still stops the merge. Then
// post-merge amends the new merge commit with the staged regeneration. A merge that stopped on a real
// conflict has no such gap: the person's `git commit` runs pre-commit, and its staged files land.
//
// The manifest is restamped by attestation, never by a plain sync. A domain is restamped only when
// each parent of the merge already carried correct digests for it (docs-manifest.mjs sync --attested).
// Both sides then vouched for the domain, so combining them is mechanical. A domain either side left
// stale keeps stale digests, and the commit is refused with the pre-commit message. The parents are
// HEAD plus the merged heads, which git names in MERGE_HEAD, or in GITHEAD_<sha> while it merges.
//
// Git calls the driver only when both sides changed a file. A merge where one side left the manifest
// alone skips it, so `reconcile` runs the same attested restamp for every merge. `rewrite` does it
// for a rebase, where no driver and no merge commit exist: the parents are the old tip and the new base.
// CODE_OPS_DIGEST_AUTOFIX=off (or 0, or false) turns reconcile and rewrite off. It does not change
// regenerate, whose attested rule is stricter than the plain sync it replaced.
//
// The derived groups apply only to `git merge` and `git pull`. The versions group needs no hook, so it
// also serves a rebase or cherry-pick. For the rest, a rebase, cherry-pick, or stash pop does
// not run the commit hooks at the right point, so those fall back to the plain text merge.
//
// The registered driver command names the script by absolute path. Git runs a merge driver from the
// top level of whichever working tree is merging, and every linked worktree shares one local config,
// so a relative path cannot resolve from all of them.
//
// Exit (regenerate, reconcile): 0 = nothing pending or all regenerated and staged, 1 = a regeneration
// failed and the conflict is back in the index. Exit (rewrite): 0 = fresh or restamped, 1 = a domain
// stays stale and the manifest is as it was. Exit (check): 0 = registered and the script exists, 1 = not.
// Exit (driver): 0 = merged, 1 = conflict. 2 = usage error.
//
// VERSIONS: two branches that each bump a plugin collide on the `version` field of its plugin.json and
// of its marketplace.json entry. The `versions` group resolves a file whose three sides differ in
// `version` fields only, with no generator and no hook. The rule, per version field:
//   - one side changed it: take that side. Neither changed it: keep it.
//   - both changed it to the same version: keep it. Git never calls the driver when the plugin.json
//     sides match, so any other result would break the parity with the marketplace entry.
//   - both changed it differently: let lo be the bump level (major, minor, patch) of the lower side
//     against the base. The result is max(ours, theirs) bumped at lo, so it differs from the base and
//     both sides. Base 2.69.0 with 2.70.0 and 2.69.1 gives 2.70.1.
// Every plugin.json and its marketplace entry see the same three versions, so they get the same
// result and the version parity check holds. Anything else falls back to the plain text merge, which
// merges or conflicts as git would without the driver: a changed field other than a version, an
// entry set that differs, a version that is not x.y.z or went below the base, or a side not written
// as 2-space JSON with a trailing newline. The driver never guesses.
// It runs only in a local checkout. CI and web-UI merges never load it and stay as they are.

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const DRIVER = 'code-ops-derived';
const SCRIPTS = dirname(fileURLToPath(import.meta.url));
// How a person runs this script from where they stand, so every message names a command that works in an adopter repo.
const SELF = `node ${relative(process.cwd(), join(SCRIPTS, 'derived-merge.mjs')).split(sep).join('/')}`;
const MARKER = 'code-ops-derived-merge-pending';
const AMEND_MARKER = 'code-ops-derived-merge-amend';
const PLACEHOLDER = 'regenerated';
const DIGEST = /("(?:sourceDigest|contentDigest)"\s*:\s*)"[^"]*"/g;

// Each group names the paths it owns, the generators that rebuild them in order, and the pathspecs
// the hook stages afterwards. `normalize` blanks the volatile stamps before the text merge, so only
// authored changes can conflict. The order is the order of regeneration: the manifest digests the
// other groups' output, so it runs last. The atlas manifest has no group on purpose. Its stamps
// record that a person re-read the prose.
export const GROUPS = [
  { id: 'vendored', match: (p) => /^plugins\/[^/]+\/scripts\//.test(p), attributes: ['plugins/*/scripts/**'], tools: [['sync-vendored.mjs']] },
  {
    id: 'hosts',
    match: (p) => p === '.agents/plugins/marketplace.json' || p.startsWith('codex-marketplace/') || p.startsWith('opencode-dist/'),
    attributes: ['.agents/plugins/marketplace.json', 'codex-marketplace/**', 'opencode-dist/**'],
    tools: [['build-codex-marketplace.mjs'], ['build-opencode-dist.mjs']],
    stage: ['.agents/plugins/marketplace.json', 'codex-marketplace/', 'opencode-dist/'],
  },
  {
    id: 'versions',
    match: (p) => p === '.claude-plugin/marketplace.json' || /^plugins\/[^/]+\/\.claude-plugin\/plugin\.json$/.test(p),
    attributes: ['.claude-plugin/marketplace.json', 'plugins/*/.claude-plugin/plugin.json'],
    tools: [],
    resolve: mergeVersions,
  },
  {
    id: 'docs-manifest',
    match: (p) => p.split('/').pop() === 'DOCS_MANIFEST.json',
    attributes: ['DOCS_MANIFEST.json'],
    tools: [['docs-manifest.mjs', 'sync', '--index', '--attested', ({ parents }) => parents.join(',')]],
    normalize: (text) => text.replace(DIGEST, `$1"${PLACEHOLDER}"`),
  },
];

// Intake files are append-only logs, so a merge keeps both sides' lines (design DEC-5).
export const UNION_ATTRIBUTES = ['"**/98 System/Records/intake.jsonl" merge=union'];

const groupRunnable = (group) => group.tools.every((tool) => existsSync(join(SCRIPTS, tool[0])));

export function attributeLines() {
  const lines = GROUPS.filter(groupRunnable).flatMap((group) => group.attributes.map((pattern) => `${pattern} merge=${DRIVER}`));
  return [...lines, ...UNION_ATTRIBUTES];
}

function git(args, options = {}) {
  const result = spawnSync('git', args, { encoding: 'utf8', ...options });
  return { status: result.status ?? 1, out: (result.stdout || '').trim(), err: (result.stderr || '').trim() };
}
const topLevel = () => resolve(git(['rev-parse', '--show-toplevel']).out);
const gitFile = (root, name) => resolve(root, git(['rev-parse', '--git-path', name], { cwd: root }).out);
const markerFile = (root) => gitFile(root, MARKER);
const headSha = (root) => git(['rev-parse', '--verify', 'HEAD'], { cwd: root }).out;
const readMarker = (file) => { try { return JSON.parse(readFileSync(file, 'utf8')); } catch { return null; } };
const sleep = (ms) => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);

const DRIVER_ARGS = 'driver %O %A %B %P';
const forward = (path) => path.split(sep).join('/');
// Git runs the driver through sh, so a double-quoted path keeps spaces and needs only these escapes.
const quote = (path) => `"${path.replace(/["\\$`]/g, '\\$&')}"`;
const DRIVER_COMMAND = new RegExp(`^node "((?:[^"\\\\]|\\\\.)*)" ${DRIVER_ARGS}$`);

// A script inside a linked worktree would vanish with that worktree, so a tracked copy is anchored
// to the main working tree, which outlives them. A script outside the repository is used as it is.
function driverScript(root, scriptsDir) {
  const script = resolve(scriptsDir, 'derived-merge.mjs');
  const inTree = relative(root, script);
  if (!inTree || inTree.startsWith('..') || isAbsolute(inTree)) return script;
  const common = git(['rev-parse', '--path-format=absolute', '--git-common-dir'], { cwd: root }).out;
  const main = common && git(['rev-parse', '--is-bare-repository'], { cwd: root }).out !== 'true' ? dirname(resolve(common)) : '';
  return main && existsSync(join(main, inTree)) ? join(main, inTree) : script;
}

export function registerDriver(root, scriptsDir = SCRIPTS) {
  git(['config', '--local', `merge.${DRIVER}.name`, 'code-ops derived-file regeneration'], { cwd: root });
  git(['config', '--local', `merge.${DRIVER}.driver`, `node ${quote(forward(driverScript(root, scriptsDir)))} ${DRIVER_ARGS}`], { cwd: root });
}

// Resolve the registered command to its script. Only an absolute path to a file that exists counts.
export function registeredScript(root) {
  const value = git(['config', '--local', '--get', `merge.${DRIVER}.driver`], { cwd: root }).out;
  if (!value) return { script: '', problem: 'missing' };
  const match = DRIVER_COMMAND.exec(value);
  if (!match) return { script: '', problem: `not a quoted absolute path: ${value}` };
  const script = match[1].replace(/\\(.)/g, '$1');
  if (!isAbsolute(script)) return { script, problem: `not an absolute path: ${script}` };
  if (!existsSync(script)) return { script, problem: `points at ${script}, which does not exist` };
  return { script, problem: '' };
}

// Append the attribute lines the repository lacks. A line that is already present is left alone.
export function ensureAttributes(root) {
  const file = join(root, '.gitattributes');
  const text = existsSync(file) ? readFileSync(file, 'utf8') : '';
  const have = new Set(text.split('\n').map((line) => line.trim()));
  const missing = attributeLines().filter((line) => !have.has(line));
  if (!missing.length) return false;
  const lead = text && !text.endsWith('\n') ? '\n' : '';
  writeFileSync(file, `${text}${lead}${text ? '\n' : ''}# Derived files regenerate and never hand-merge (scripts/derived-merge.mjs). Intake files keep both sides' lines.\n${missing.join('\n')}\n`);
  return true;
}

export function driverRegistered(root) {
  const { script, problem } = registeredScript(root);
  const text = existsSync(join(root, '.gitattributes')) ? readFileSync(join(root, '.gitattributes'), 'utf8') : '';
  const have = new Set(text.split('\n').map((line) => line.trim()));
  return { registered: !problem, script, problem, attributes: attributeLines().every((line) => have.has(line)) };
}

// Only `git merge` and `git pull` reach a commit hook after the whole tree is merged.
function inMergeCommand() {
  const action = process.env.GIT_REFLOG_ACTION || '';
  if (!/^(merge|pull)( |$)/.test(action)) return false;
  return !['rebase-merge', 'rebase-apply'].some((name) => existsSync(resolve(git(['rev-parse', '--git-path', name]).out)));
}

// The heads a merge brings in. A merge that stopped for a person leaves MERGE_HEAD. While git still
// merges, the driver and pre-merge-commit see no such file, only a GITHEAD_<sha> variable per head.
function mergeHeads(root) {
  const file = gitFile(root, 'MERGE_HEAD');
  if (existsSync(file)) return readFileSync(file, 'utf8').split('\n').map((line) => line.trim()).filter(Boolean).sort();
  if (!inMergeCommand()) return [];
  return Object.keys(process.env).flatMap((key) => /^GITHEAD_([0-9a-f]{40}|[0-9a-f]{64})$/.exec(key)?.[1] ?? []).sort();
}

const SEMVER = /^(\d+)\.(\d+)\.(\d+)$/;
const parseVersion = (text) => { const match = typeof text === 'string' && SEMVER.exec(text); return match ? match.slice(1).map(Number) : null; };
const compareVersions = (a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2];
// 0 = major, 1 = minor, 2 = patch: the first part where `to` departs from `from`.
const bumpLevel = (from, to) => (from[0] !== to[0] ? 0 : from[1] !== to[1] ? 1 : 2);
const bumpAt = (version, level) => version.map((part, index) => (index < level ? part : index === level ? part + 1 : 0));

// The merged version text, or null when the rule does not apply.
function mergeVersion(base, ours, theirs) {
  if (ours === base) return theirs;
  if (theirs === base || ours === theirs) return ours;
  const [b, o, t] = [base, ours, theirs].map(parseVersion);
  if (!b || !o || !t || compareVersions(o, b) <= 0 || compareVersions(t, b) <= 0) return null;
  const lower = compareVersions(o, t) <= 0 ? o : t;
  const higher = lower === o ? t : o;
  return bumpAt(higher, bumpLevel(b, lower)).join('.');
}

// Split a plugin.json or marketplace.json into its version fields and everything else.
function versionSlots(text, path) {
  let doc;
  try { doc = JSON.parse(text); } catch { return null; }
  if (`${JSON.stringify(doc, null, 2)}\n` !== text) return null;
  let slots;
  if (path !== '.claude-plugin/marketplace.json') {
    const { version, ...rest } = doc;
    slots = { doc, rest, versions: { '': version } };
  } else {
    if (!Array.isArray(doc.plugins) || new Set(doc.plugins.map((entry) => entry?.name)).size !== doc.plugins.length) return null;
    slots = { doc, rest: { ...doc, plugins: doc.plugins.map(({ version, ...entry }) => entry) }, versions: Object.fromEntries(doc.plugins.map((entry) => [entry.name, entry.version])) };
  }
  return Object.values(slots.versions).every((version) => typeof version === 'string') ? slots : null;
}

// Write the merged file over `ours` and return true, or return false and leave every file alone.
function mergeVersions(base, ours, theirs, path) {
  const [b, o, t] = [base, ours, theirs].map((file) => versionSlots(readFileSync(file, 'utf8'), path));
  if (!b || !o || !t) return false;
  if (JSON.stringify(b.rest) !== JSON.stringify(o.rest) || JSON.stringify(b.rest) !== JSON.stringify(t.rest)) return false;
  const merged = {};
  for (const key of Object.keys(o.versions)) {
    merged[key] = mergeVersion(b.versions[key], o.versions[key], t.versions[key]);
    if (merged[key] === null) return false;
  }
  if (path === '.claude-plugin/marketplace.json') for (const entry of o.doc.plugins) entry.version = merged[entry.name];
  else o.doc.version = merged[''];
  writeFileSync(ours, `${JSON.stringify(o.doc, null, 2)}\n`);
  return true;
}

function textMerge(ours, base, theirs, path) {
  const result = git(['merge-file', '-L', `${path} (ours)`, '-L', `${path} (base)`, '-L', `${path} (theirs)`, ours, base, theirs]);
  return result.status === 0 ? 0 : 1;
}

function recordPending(root, path, base, ours, theirs) {
  const head = headSha(root);
  const blob = (file) => (readFileSync(file).length ? git(['hash-object', '-w', '--no-filters', '--', file], { cwd: root }).out : null);
  const entry = { base: blob(base), ours: blob(ours), theirs: blob(theirs) };
  if (!head || !entry.ours || !entry.theirs) throw new Error('cannot record the merge inputs');
  const file = markerFile(root);
  let state = readMarker(file);
  const parents = [head, ...mergeHeads(root)];
  if (!state || state.head !== head) state = { head, parents, entries: {} };
  else if (!(state.parents?.length > 1)) state.parents = parents;
  state.entries[path] = entry;
  writeFileSync(file, JSON.stringify(state));
}

function driver([base, ours, theirs, path]) {
  const group = GROUPS.find((candidate) => candidate.match(path));
  if (group?.resolve) return group.resolve(base, ours, theirs, path) ? 0 : textMerge(ours, base, theirs, path);
  if (!group || !groupRunnable(group) || !inMergeCommand()) return textMerge(ours, base, theirs, path);
  try { recordPending(topLevel(), path, base, ours, theirs); } catch { return textMerge(ours, base, theirs, path); }
  if (!group.normalize) return 0;
  for (const file of [base, ours, theirs]) writeFileSync(file, group.normalize(readFileSync(file, 'utf8')));
  return textMerge(ours, base, theirs, path);
}

// A tool argument may be a function of the context, which holds the merge parents. A tool that needs
// the parents fails closed when fewer than two are known: attestation needs both sides.
// A "left stale" line from the manifest tool goes to ctx.notes, so the caller can name the domains.
function runTools(group, root, ctx) {
  for (const [tool, ...args] of group.tools) {
    if (args.some((arg) => typeof arg === 'function') && ctx.parents.length < 2) return `${tool} needs both merge parents, and git named only ${ctx.parents.length}`;
    const result = spawnSync(process.execPath, [join(SCRIPTS, tool), ...args.map((arg) => (typeof arg === 'function' ? arg(ctx) : arg))], { cwd: root, encoding: 'utf8' });
    if (result.status !== 0) return `${tool} exited ${result.status ?? 'without a status'}: ${`${result.stdout || ''}${result.stderr || ''}`.trim().split('\n').slice(-6).join(' | ')}`;
    ctx.notes.push(...(result.stdout || '').split('\n').filter((line) => line.startsWith('left stale')));
  }
  return '';
}

const toolCommand = (name, ...args) => ['node', relative(process.cwd(), join(SCRIPTS, name)).split(sep).join('/'), ...args].join(' ');
// Domains the attested rule left alone still hold stale digests, and a driver merge left a placeholder in them.
function reportStale(notes) {
  if (!notes.length) return;
  console.error([`note: the merge did not stamp these documentation domains, because a parent did not carry correct digests for them.`,
    `Their digests are stale, and a merged placeholder reads "${PLACEHOLDER}". After you review the cause, stamp them with: ${toolCommand('docs-manifest.mjs', 'sync')}`,
    ...notes.map((line) => `  ${line}`)].join('\n'));
}
const autofixOff = () => ['off', '0', 'false'].includes((process.env.CODE_OPS_DIGEST_AUTOFIX || '').toLowerCase());

// The tree the commit must hold. A merge commit written from the earlier tree gets amended.
const writeAmendMarker = (root, head) => writeFileSync(gitFile(root, AMEND_MARKER), JSON.stringify({ head, tree: git(['write-tree'], { cwd: root }).out }));

// git add takes the index lock and never waits, so a busy lock is the one retried failure.
function stage(root, pathspecs) {
  let last = '';
  for (const delay of [0, 500, 1000, 2000]) {
    if (delay) sleep(delay);
    const result = git(['add', '-A', '--', ...pathspecs], { cwd: root });
    if (result.status === 0) return '';
    last = result.err;
    if (!last.includes('index.lock')) break;
  }
  return `git add failed: ${last.split('\n')[0]}`;
}

// Put the file back into the unmerged state, so a commit refuses until someone resolves it.
function restoreConflicts(root, entries) {
  const lines = [];
  for (const [path, entry] of entries) {
    const mode = git(['ls-files', '-s', '--', path], { cwd: root }).out.split(/\s/)[0] || '100644';
    lines.push(`0 ${'0'.repeat(entry.ours.length)}\t${path}`);
    [entry.base, entry.ours, entry.theirs].forEach((blob, index) => { if (blob) lines.push(`${mode} ${blob} ${index + 1}\t${path}`); });
  }
  return git(['update-index', '--index-info'], { cwd: root, input: `${lines.join('\n')}\n` }).status === 0;
}

function regenerate(amendAfter) {
  const root = topLevel();
  const file = markerFile(root);
  const state = readMarker(file);
  if (!state) return 0;
  if (state.head !== headSha(root)) { rmSync(file, { force: true }); return 0; }
  // A generator refuses a path the index lists as unmerged, so a retry stages the flagged ones first.
  const unmerged = [...new Set(git(['ls-files', '-u', '-z'], { cwd: root }).out.split('\0').map((line) => line.split('\t')[1]).filter(Boolean))];
  const flagged = unmerged.filter((path) => path in state.entries);
  if (flagged.length) stage(root, flagged);
  const failures = [];
  let blocked = '';
  const ctx = { parents: state.parents?.length > 1 ? state.parents : [state.head, ...mergeHeads(root)], notes: [] };
  for (const group of GROUPS) {
    const paths = Object.keys(state.entries).filter((path) => group.match(path));
    if (!paths.length) continue;
    // Later groups read what earlier groups wrote, so one failure stops them all.
    const why = blocked ? `skipped, the ${blocked} regeneration failed first` : runTools(group, root, ctx) || stage(root, group.stage || paths);
    if (why) { blocked ||= group.id; failures.push({ group: group.id, paths, why }); }
  }
  reportStale(ctx.notes);
  if (!failures.length) {
    rmSync(file, { force: true });
    if (amendAfter) writeAmendMarker(root, state.head);
    return 0;
  }
  const failed = new Set(failures.flatMap((failure) => failure.paths));
  const restored = restoreConflicts(root, Object.entries(state.entries).filter(([path]) => failed.has(path)));
  state.entries = Object.fromEntries(Object.entries(state.entries).filter(([path]) => failed.has(path)));
  writeFileSync(file, JSON.stringify(state));
  const lines = ['x derived-file regeneration failed. The merge cannot be committed with a stale derived file.'];
  for (const failure of failures) lines.push(`  ${failure.group}: ${failure.why}`, ...failure.paths.slice(0, 5).map((path) => `    ${path}`));
  lines.push(restored ? `The listed files are conflicted again. Fix the cause and stage the fix, because the generators read the index. Then run: ${SELF} regenerate` : 'The index could not be restored. Run: git status');
  lines.push('That command regenerates and stages them. Then finish the merge with git commit.');
  console.error(lines.join('\n'));
  return 1;
}

// post-merge: the merge commit exists and holds the pre-regeneration tree, while the index holds the
// regenerated one. Fold the difference into that commit, and only when it is exactly that difference.
function amend() {
  const root = topLevel();
  const file = gitFile(root, AMEND_MARKER);
  const pending = readMarker(file);
  if (!pending) return 0;
  rmSync(file, { force: true });
  const parents = git(['rev-list', '--parents', '-n1', 'HEAD'], { cwd: root }).out.split(' ').slice(1);
  const expected = parents.length === 2 && parents[0] === pending.head && git(['write-tree'], { cwd: root }).out === pending.tree;
  if (!expected || git(['rev-parse', 'HEAD^{tree}'], { cwd: root }).out === pending.tree) return 0;
  const replaced = replaceHead(root, pending.tree, parents, 'merge: regenerated derived files');
  if (!replaced) return 0;
  console.error(`x the merge commit lacks the regenerated derived files, which are staged. Run: git commit --amend --no-edit\n  ${replaced}`);
  return 1;
}

// Write HEAD again over `tree`, keeping its author and message. `git commit --amend` refuses inside
// post-merge and re-enters pre-commit inside post-rewrite, so this writes the commit object directly.
// Returns '' when HEAD moved, else the first line of the failure.
function replaceHead(root, tree, parents, reflog) {
  const show = (format) => git(['log', '-1', `--format=${format}`], { cwd: root }).out;
  const env = { ...process.env, GIT_AUTHOR_NAME: show('%an'), GIT_AUTHOR_EMAIL: show('%ae'), GIT_AUTHOR_DATE: show('%aI') };
  const message = git(['log', '-1', '--format=%B'], { cwd: root, encoding: 'utf8' }).out;
  const made = git(['commit-tree', tree, ...parents.flatMap((parent) => ['-p', parent]), '-F', '-'], { cwd: root, env, input: `${message}\n` });
  const moved = made.status === 0 && git(['update-ref', '-m', reflog, 'HEAD', made.out, headSha(root)], { cwd: root });
  return moved && moved.status === 0 ? '' : (made.err || (moved && moved.err) || 'git could not write the commit').split('\n')[0];
}

// The attested restamp that reconcile and rewrite share. It runs only on a manifest the index and the
// working tree agree on, because the tool writes the working file and the caller stages it whole.
// `skip` is why nothing ran, `dirty` marks the case a person fixes, and `why` is a tool failure.
function attestedRestamp(root, revs) {
  const group = GROUPS.find((candidate) => candidate.id === 'docs-manifest');
  if (!groupRunnable(group)) return { skip: 'docs-manifest.mjs is not installed here' };
  const paths = git(['ls-files', '-z', '--', '*DOCS_MANIFEST.json'], { cwd: root }).out.split('\0').filter((path) => path && group.match(path));
  if (!paths.length) return { skip: '' };
  if (git(['ls-files', '-u'], { cwd: root }).out) return { skip: 'the index has unmerged paths' };
  if (git(['diff', '--quiet', '--', ...paths], { cwd: root }).status !== 0) return { skip: `${paths[0]} has unstaged edits`, dirty: true };
  const ctx = { parents: revs, notes: [] };
  return { paths, ctx, why: runTools(group, root, ctx) };
}

// Merge-time restamp for every merge, including the one-sided merge that never calls the driver. It
// stages only the manifest, and never refuses: the freshness check in pre-commit is the gate. With
// --amend-after it records the tree that post-merge folds into the merge commit.
function reconcile(amendAfter) {
  if (autofixOff()) return 0;
  const root = topLevel();
  const head = headSha(root);
  const heads = mergeHeads(root);
  if (!head || !heads.length) return 0;
  const done = attestedRestamp(root, [head, ...heads]);
  if (done.dirty) console.error(`note: ${done.skip}, so the merge did not restamp it. Stage or discard them, then run: ${SELF} reconcile`);
  if (done.skip || !done.paths) return 0;
  if (done.why) { console.error(`note: the merge could not restamp the manifest: ${done.why}`); return 0; }
  const staged = stage(root, done.paths);
  if (staged) { console.error(`note: ${staged}`); return 0; }
  reportStale(done.ctx.notes);
  if (amendAfter) writeAmendMarker(root, head);
  return 0;
}

// post-rewrite: a rebase has no merge commit and no driver, so the parents are the old tip, which the
// author stamped, and the new base, which CI stamped. The restamped manifest is staged, and with
// --amend it also replaces HEAD without running hooks. The result must pass check --index, or the
// manifest goes back to HEAD, so a rewrite never leaves a half-stamped file behind.
function rewrite(args) {
  const [old, base, amendHead] = args;
  if (autofixOff()) return 0;
  const root = topLevel();
  const command = `${SELF} rewrite --old ${old} --base ${base}${amendHead ? ' --amend' : ''}`;
  const commit = (rev) => git(['rev-parse', '--verify', '--quiet', `${rev}^{commit}`], { cwd: root }).out;
  if (!commit(old) || !commit(base)) { console.error(`x rewrite: ${commit(old) ? base : old} is not a commit`); return 2; }
  if (git(['diff', '--cached', '--quiet'], { cwd: root }).status !== 0) { console.error(`note: the index holds staged changes, so the rewrite did not restamp the manifest. Commit or unstage them, then run: ${command}`); return 0; }
  const done = attestedRestamp(root, [commit(old), commit(base)]);
  if (done.dirty) console.error(`note: ${done.skip}, so the rewrite did not restamp it. Stage or discard them, then run: ${command}`);
  if (done.skip || !done.paths) return 0;
  if (done.why) { console.error(`x rewrite: ${done.why}`); return 1; }
  const changed = git(['diff', '--quiet', '--', ...done.paths], { cwd: root }).status !== 0;
  const stale = () => { reportStale(done.ctx.notes); return 1; };
  if (!changed) return done.ctx.notes.length ? stale() : 0;
  const staged = stage(root, done.paths);
  const verdict = staged ? { status: 1 } : spawnSync(process.execPath, [join(SCRIPTS, 'docs-manifest.mjs'), 'check', '--index'], { cwd: root, encoding: 'utf8' });
  if (verdict.status !== 0) {
    git(['restore', '--source=HEAD', '--staged', '--worktree', '--', ...done.paths], { cwd: root });
    if (staged) console.error(`x rewrite: ${staged}`);
    return stale();
  }
  if (!amendHead) { console.log(`ok restamped the manifest digests and staged them. Fold them into HEAD with: git commit --amend --no-edit`); return 0; }
  const parents = git(['rev-list', '--parents', '-n1', 'HEAD'], { cwd: root }).out.split(' ').slice(1);
  const replaced = replaceHead(root, git(['write-tree'], { cwd: root }).out, parents, 'rewrite: restamped manifest digests');
  if (replaced) { console.error(`x the restamped manifest is staged but HEAD was not amended. Run: git commit --amend --no-edit\n  ${replaced}`); return 1; }
  console.log('ok restamped the manifest digests and amended HEAD');
  return 0;
}

const isEntry = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isEntry) {
  const [command, ...rest] = process.argv.slice(2);
  if (command === 'driver' && rest.length === 4) process.exit(driver(rest));
  if (command === 'regenerate' && (!rest.length || (rest.length === 1 && rest[0] === '--amend-after'))) process.exit(regenerate(rest.length === 1));
  if (command === 'amend' && !rest.length) process.exit(amend());
  if (command === 'reconcile' && (!rest.length || (rest.length === 1 && rest[0] === '--amend-after'))) process.exit(reconcile(rest.length === 1));
  if (command === 'rewrite' && rest[0] === '--old' && rest[2] === '--base' && rest[1] && rest[3] && !rest[1].startsWith('-') && !rest[3].startsWith('-') && (rest.length === 4 || (rest.length === 5 && rest[4] === '--amend'))) {
    process.exit(rewrite([rest[1], rest[3], rest.length === 5]));
  }
  if (command === 'install' && !rest.length) {
    const root = topLevel();
    registerDriver(root);
    const changed = ensureAttributes(root);
    console.log(`Registered merge driver ${DRIVER}${changed ? ' and added its attributes to .gitattributes' : ''}.`);
    process.exit(0);
  }
  if (command === 'check' && !rest.length) {
    const state = driverRegistered(topLevel());
    if (state.registered && state.attributes) { console.log(`OK merge driver ${DRIVER} is registered.`); process.exit(0); }
    console.error(`x merge driver ${DRIVER} is not fully installed (driver ${state.registered ? 'set' : state.problem}, attributes ${state.attributes ? 'set' : 'missing'}). Run: ${SELF} install`);
    process.exit(1);
  }
  console.error(`usage: ${SELF} install | check | regenerate [--amend-after] | amend | reconcile [--amend-after] | rewrite --old <rev> --base <rev> [--amend] | driver <base> <ours> <theirs> <path>`);
  process.exit(2);
}
