#!/usr/bin/env node
// Derived-file merge driver. A derived file (the documentation manifest, the host
// distributions, the vendored script copies) is regenerated from its sources and never
// hand-merged, so two branches that both regenerated it must not conflict on it.
//
//   node scripts/derived-merge.mjs install       register the driver and its attributes
//   node scripts/derived-merge.mjs check         exit 1 unless the driver is registered
//   node scripts/derived-merge.mjs regenerate    run from pre-commit and pre-merge-commit
//   node scripts/derived-merge.mjs amend         run from post-merge
//   node scripts/derived-merge.mjs driver %O %A %B %P    git calls this, never a person
//
// WHY two phases: git runs a merge driver once per file, before the merged tree exists on disk.
// A generator that ran inside the driver would read half-merged sources and write a wrong file.
// So the driver only records the path, and the merge result is regenerated by the commit hooks
// after every file, derived or not, has its merged content. A regeneration that fails restores the
// conflict in the index, so the merge cannot be committed with a stale file.
//
// A clean automatic merge needs one more step. Git writes that merge commit from the tree it
// merged before the pre-merge-commit hook ran, so the hook's regenerated files stay staged and miss
// the commit. The hook regenerates anyway, because a failure there still stops the merge. Then
// post-merge amends the new merge commit with the staged regeneration. A merge that stopped on a real
// conflict has no such gap: the person's `git commit` runs pre-commit, and its staged files land.
//
// The driver applies only to `git merge` and `git pull`. A rebase, cherry-pick, or stash pop does
// not run the commit hooks at the right point, so those fall back to the plain text merge.
//
// The registered driver command names the script by absolute path. Git runs a merge driver from the
// top level of whichever working tree is merging, and every linked worktree shares one local config,
// so a relative path cannot resolve from all of them.
//
// Exit (regenerate): 0 = nothing pending or all regenerated and staged, 1 = a regeneration failed
// and the conflict is back in the index. Exit (check): 0 = registered and the script exists, 1 = not.
// Exit (driver): 0 = merged, 1 = conflict. 2 = usage error.

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const DRIVER = 'code-ops-derived';
const SCRIPTS = dirname(fileURLToPath(import.meta.url));
// How a person runs this script from where they stand, so every message names a command that works in an adopter repo.
const SELF = `node ${relative(process.cwd(), join(SCRIPTS, 'derived-merge.mjs')).split(sep).join('/')}`;
const MARKER = 'code-ops-derived-merge-pending';
const AMEND_MARKER = 'code-ops-derived-merge-amend';
const PLACEHOLDER = 'regenerated';
const DIGEST = /("(?:sourceDigest|contentDigest)"\s*:\s*)"[^"]*"/g;

// Each group names the paths it owns, the generators that rebuild them in order, and the pathspecs
// the hook stages afterwards. `normalize` blanks the volatile stamps before the text merge, so only
// authored changes can conflict. The order is the order of regeneration: the manifest digests the
// other groups' output, so it runs last. The atlas manifest has no group on purpose. Its stamps
// record that a person re-read the prose.
export const GROUPS = [
  { id: 'vendored', match: (p) => /^plugins\/[^/]+\/scripts\//.test(p), attributes: ['plugins/*/scripts/**'], tools: [['sync-vendored.mjs']] },
  {
    id: 'hosts',
    match: (p) => p === '.agents/plugins/marketplace.json' || p.startsWith('codex-marketplace/') || p.startsWith('opencode-dist/'),
    attributes: ['.agents/plugins/marketplace.json', 'codex-marketplace/**', 'opencode-dist/**'],
    tools: [['build-codex-marketplace.mjs'], ['build-opencode-dist.mjs']],
    stage: ['.agents/plugins/marketplace.json', 'codex-marketplace/', 'opencode-dist/'],
  },
  {
    id: 'docs-manifest',
    match: (p) => p.split('/').pop() === 'DOCS_MANIFEST.json',
    attributes: ['DOCS_MANIFEST.json'],
    tools: [['docs-manifest.mjs', 'sync']],
    normalize: (text) => text.replace(DIGEST, `$1"${PLACEHOLDER}"`),
  },
];

// Intake files are append-only logs, so a merge keeps both sides' lines (design DEC-5).
export const UNION_ATTRIBUTES = ['"**/98 System/Records/intake.jsonl" merge=union'];

const groupRunnable = (group) => group.tools.every((tool) => existsSync(join(SCRIPTS, tool[0])));

export function attributeLines() {
  const lines = GROUPS.filter(groupRunnable).flatMap((group) => group.attributes.map((pattern) => `${pattern} merge=${DRIVER}`));
  return [...lines, ...UNION_ATTRIBUTES];
}

function git(args, options = {}) {
  const result = spawnSync('git', args, { encoding: 'utf8', ...options });
  return { status: result.status ?? 1, out: (result.stdout || '').trim(), err: (result.stderr || '').trim() };
}
const topLevel = () => resolve(git(['rev-parse', '--show-toplevel']).out);
const gitFile = (root, name) => resolve(root, git(['rev-parse', '--git-path', name], { cwd: root }).out);
const markerFile = (root) => gitFile(root, MARKER);
const headSha = (root) => git(['rev-parse', '--verify', 'HEAD'], { cwd: root }).out;
const readMarker = (file) => { try { return JSON.parse(readFileSync(file, 'utf8')); } catch { return null; } };
const sleep = (ms) => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);

const DRIVER_ARGS = 'driver %O %A %B %P';
const forward = (path) => path.split(sep).join('/');
// Git runs the driver through sh, so a double-quoted path keeps spaces and needs only these escapes.
const quote = (path) => `"${path.replace(/["\\$`]/g, '\\$&')}"`;
const DRIVER_COMMAND = new RegExp(`^node "((?:[^"\\\\]|\\\\.)*)" ${DRIVER_ARGS}$`);

// A script inside a linked worktree would vanish with that worktree, so a tracked copy is anchored
// to the main working tree, which outlives them. A script outside the repository is used as it is.
function driverScript(root, scriptsDir) {
  const script = resolve(scriptsDir, 'derived-merge.mjs');
  const inTree = relative(root, script);
  if (!inTree || inTree.startsWith('..') || isAbsolute(inTree)) return script;
  const common = git(['rev-parse', '--path-format=absolute', '--git-common-dir'], { cwd: root }).out;
  const main = common && git(['rev-parse', '--is-bare-repository'], { cwd: root }).out !== 'true' ? dirname(resolve(common)) : '';
  return main && existsSync(join(main, inTree)) ? join(main, inTree) : script;
}

export function registerDriver(root, scriptsDir = SCRIPTS) {
  git(['config', '--local', `merge.${DRIVER}.name`, 'code-ops derived-file regeneration'], { cwd: root });
  git(['config', '--local', `merge.${DRIVER}.driver`, `node ${quote(forward(driverScript(root, scriptsDir)))} ${DRIVER_ARGS}`], { cwd: root });
}

// Resolve the registered command to its script. Only an absolute path to a file that exists counts.
export function registeredScript(root) {
  const value = git(['config', '--local', '--get', `merge.${DRIVER}.driver`], { cwd: root }).out;
  if (!value) return { script: '', problem: 'missing' };
  const match = DRIVER_COMMAND.exec(value);
  if (!match) return { script: '', problem: `not a quoted absolute path: ${value}` };
  const script = match[1].replace(/\\(.)/g, '$1');
  if (!isAbsolute(script)) return { script, problem: `not an absolute path: ${script}` };
  if (!existsSync(script)) return { script, problem: `points at ${script}, which does not exist` };
  return { script, problem: '' };
}

// Append the attribute lines the repository lacks. A line that is already present is left alone.
export function ensureAttributes(root) {
  const file = join(root, '.gitattributes');
  const text = existsSync(file) ? readFileSync(file, 'utf8') : '';
  const have = new Set(text.split('\n').map((line) => line.trim()));
  const missing = attributeLines().filter((line) => !have.has(line));
  if (!missing.length) return false;
  const lead = text && !text.endsWith('\n') ? '\n' : '';
  writeFileSync(file, `${text}${lead}${text ? '\n' : ''}# Derived files regenerate and never hand-merge (scripts/derived-merge.mjs). Intake files keep both sides' lines.\n${missing.join('\n')}\n`);
  return true;
}

export function driverRegistered(root) {
  const { script, problem } = registeredScript(root);
  const text = existsSync(join(root, '.gitattributes')) ? readFileSync(join(root, '.gitattributes'), 'utf8') : '';
  const have = new Set(text.split('\n').map((line) => line.trim()));
  return { registered: !problem, script, problem, attributes: attributeLines().every((line) => have.has(line)) };
}

// Only `git merge` and `git pull` reach a commit hook after the whole tree is merged.
function inMergeCommand() {
  const action = process.env.GIT_REFLOG_ACTION || '';
  if (!/^(merge|pull)( |$)/.test(action)) return false;
  return !['rebase-merge', 'rebase-apply'].some((name) => existsSync(resolve(git(['rev-parse', '--git-path', name]).out)));
}

function textMerge(ours, base, theirs, path) {
  const result = git(['merge-file', '-L', `${path} (ours)`, '-L', `${path} (base)`, '-L', `${path} (theirs)`, ours, base, theirs]);
  return result.status === 0 ? 0 : 1;
}

function recordPending(root, path, base, ours, theirs) {
  const head = headSha(root);
  const blob = (file) => (readFileSync(file).length ? git(['hash-object', '-w', '--no-filters', '--', file], { cwd: root }).out : null);
  const entry = { base: blob(base), ours: blob(ours), theirs: blob(theirs) };
  if (!head || !entry.ours || !entry.theirs) throw new Error('cannot record the merge inputs');
  const file = markerFile(root);
  let state = readMarker(file);
  if (!state || state.head !== head) state = { head, entries: {} };
  state.entries[path] = entry;
  writeFileSync(file, JSON.stringify(state));
}

function driver([base, ours, theirs, path]) {
  const group = GROUPS.find((candidate) => candidate.match(path));
  if (!group || !groupRunnable(group) || !inMergeCommand()) return textMerge(ours, base, theirs, path);
  try { recordPending(topLevel(), path, base, ours, theirs); } catch { return textMerge(ours, base, theirs, path); }
  if (!group.normalize) return 0;
  for (const file of [base, ours, theirs]) writeFileSync(file, group.normalize(readFileSync(file, 'utf8')));
  return textMerge(ours, base, theirs, path);
}

function runTools(group, root) {
  for (const [tool, ...args] of group.tools) {
    const result = spawnSync(process.execPath, [join(SCRIPTS, tool), ...args], { cwd: root, encoding: 'utf8' });
    if (result.status !== 0) return `${tool} exited ${result.status ?? 'without a status'}: ${`${result.stdout || ''}${result.stderr || ''}`.trim().split('\n').slice(-6).join(' | ')}`;
  }
  return '';
}

// git add takes the index lock and never waits, so a busy lock is the one retried failure.
function stage(root, pathspecs) {
  let last = '';
  for (const delay of [0, 500, 1000, 2000]) {
    if (delay) sleep(delay);
    const result = git(['add', '-A', '--', ...pathspecs], { cwd: root });
    if (result.status === 0) return '';
    last = result.err;
    if (!last.includes('index.lock')) break;
  }
  return `git add failed: ${last.split('\n')[0]}`;
}

// Put the file back into the unmerged state, so a commit refuses until someone resolves it.
function restoreConflicts(root, entries) {
  const lines = [];
  for (const [path, entry] of entries) {
    const mode = git(['ls-files', '-s', '--', path], { cwd: root }).out.split(/\s/)[0] || '100644';
    lines.push(`0 ${'0'.repeat(entry.ours.length)}\t${path}`);
    [entry.base, entry.ours, entry.theirs].forEach((blob, index) => { if (blob) lines.push(`${mode} ${blob} ${index + 1}\t${path}`); });
  }
  return git(['update-index', '--index-info'], { cwd: root, input: `${lines.join('\n')}\n` }).status === 0;
}

function regenerate(amendAfter) {
  const root = topLevel();
  const file = markerFile(root);
  const state = readMarker(file);
  if (!state) return 0;
  if (state.head !== headSha(root)) { rmSync(file, { force: true }); return 0; }
  // A generator refuses a path the index lists as unmerged, so a retry stages the flagged ones first.
  const unmerged = [...new Set(git(['ls-files', '-u', '-z'], { cwd: root }).out.split('\0').map((line) => line.split('\t')[1]).filter(Boolean))];
  const flagged = unmerged.filter((path) => path in state.entries);
  if (flagged.length) stage(root, flagged);
  const failures = [];
  let blocked = '';
  for (const group of GROUPS) {
    const paths = Object.keys(state.entries).filter((path) => group.match(path));
    if (!paths.length) continue;
    // Later groups read what earlier groups wrote, so one failure stops them all.
    const why = blocked ? `skipped, the ${blocked} regeneration failed first` : runTools(group, root) || stage(root, group.stage || paths);
    if (why) { blocked ||= group.id; failures.push({ group: group.id, paths, why }); }
  }
  if (!failures.length) {
    rmSync(file, { force: true });
    // Record the tree the commit must hold. A merge commit written from the earlier tree gets amended.
    if (amendAfter) writeFileSync(gitFile(root, AMEND_MARKER), JSON.stringify({ head: state.head, tree: git(['write-tree'], { cwd: root }).out }));
    return 0;
  }
  const failed = new Set(failures.flatMap((failure) => failure.paths));
  const restored = restoreConflicts(root, Object.entries(state.entries).filter(([path]) => failed.has(path)));
  state.entries = Object.fromEntries(Object.entries(state.entries).filter(([path]) => failed.has(path)));
  writeFileSync(file, JSON.stringify(state));
  const lines = ['x derived-file regeneration failed. The merge cannot be committed with a stale derived file.'];
  for (const failure of failures) lines.push(`  ${failure.group}: ${failure.why}`, ...failure.paths.slice(0, 5).map((path) => `    ${path}`));
  lines.push(restored ? `The listed files are conflicted again. Fix the cause, then run: ${SELF} regenerate` : 'The index could not be restored. Run: git status');
  lines.push('That command regenerates and stages them. Then finish the merge with git commit.');
  console.error(lines.join('\n'));
  return 1;
}

// post-merge: the merge commit exists and holds the pre-regeneration tree, while the index holds the
// regenerated one. Fold the difference into that commit, and only when it is exactly that difference.
function amend() {
  const root = topLevel();
  const file = gitFile(root, AMEND_MARKER);
  const pending = readMarker(file);
  if (!pending) return 0;
  rmSync(file, { force: true });
  const parents = git(['rev-list', '--parents', '-n1', 'HEAD'], { cwd: root }).out.split(' ').slice(1);
  const expected = parents.length === 2 && parents[0] === pending.head && git(['write-tree'], { cwd: root }).out === pending.tree;
  if (!expected || git(['rev-parse', 'HEAD^{tree}'], { cwd: root }).out === pending.tree) return 0;
  // `git commit --amend` refuses inside post-merge, so write the commit object directly.
  const show = (format) => git(['log', '-1', `--format=${format}`], { cwd: root }).out;
  const env = { ...process.env, GIT_AUTHOR_NAME: show('%an'), GIT_AUTHOR_EMAIL: show('%ae'), GIT_AUTHOR_DATE: show('%aI') };
  const message = git(['log', '-1', '--format=%B'], { cwd: root, encoding: 'utf8' }).out;
  const made = git(['commit-tree', pending.tree, '-p', parents[0], '-p', parents[1], '-F', '-'], { cwd: root, env, input: `${message}\n` });
  const moved = made.status === 0 && git(['update-ref', '-m', 'merge: regenerated derived files', 'HEAD', made.out, headSha(root)], { cwd: root });
  if (moved && moved.status === 0) return 0;
  console.error(`x the merge commit lacks the regenerated derived files, which are staged. Run: git commit --amend --no-edit\n  ${(made.err || (moved && moved.err) || '').split('\n')[0]}`);
  return 1;
}

const isEntry = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isEntry) {
  const [command, ...rest] = process.argv.slice(2);
  if (command === 'driver' && rest.length === 4) process.exit(driver(rest));
  if (command === 'regenerate' && (!rest.length || (rest.length === 1 && rest[0] === '--amend-after'))) process.exit(regenerate(rest.length === 1));
  if (command === 'amend' && !rest.length) process.exit(amend());
  if (command === 'install' && !rest.length) {
    const root = topLevel();
    registerDriver(root);
    const changed = ensureAttributes(root);
    console.log(`Registered merge driver ${DRIVER}${changed ? ' and added its attributes to .gitattributes' : ''}.`);
    process.exit(0);
  }
  if (command === 'check' && !rest.length) {
    const state = driverRegistered(topLevel());
    if (state.registered && state.attributes) { console.log(`OK merge driver ${DRIVER} is registered.`); process.exit(0); }
    console.error(`x merge driver ${DRIVER} is not fully installed (driver ${state.registered ? 'set' : state.problem}, attributes ${state.attributes ? 'set' : 'missing'}). Run: ${SELF} install`);
    process.exit(1);
  }
  console.error(`usage: ${SELF} install | check | regenerate [--amend-after] | amend | driver <base> <ours> <theirs> <path>`);
  process.exit(2);
}
